--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Janeiro-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIME
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIME" 
   (	"ID_TIME" NUMBER, 
	"NOME" VARCHAR2(400 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TECNICO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TECNICO" 
   (	"ID_TECNICO" NUMBER, 
	"NOME" VARCHAR2(400 BYTE), 
	"DT_BASCIMENTO" DATE, 
	"SALARIO" NUMBER(18,2), 
	"ID_TIME" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOGADOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."JOGADOR" 
   (	"ID_JOGADOR" NUMBER, 
	"NOME" VARCHAR2(400 BYTE), 
	"DT_NASCIMENTO" DATE, 
	"SALARIO" NUMBER(18,2), 
	"ID_TIME" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TIME
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_TIME" ON "SYSTEM"."TIME" ("ID_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TECNICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_TECNICO" ON "SYSTEM"."TECNICO" ("ID_TECNICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_JOGADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_JOGADOR" ON "SYSTEM"."JOGADOR" ("ID_JOGADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIME" ADD CONSTRAINT "PK_TIME" PRIMARY KEY ("ID_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TIME" MODIFY ("ID_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TECNICO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TECNICO" ADD CONSTRAINT "PK_TECNICO" PRIMARY KEY ("ID_TECNICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TECNICO" MODIFY ("DT_BASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TECNICO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TECNICO" MODIFY ("ID_TECNICO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOGADOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."JOGADOR" ADD CONSTRAINT "PK_JOGADOR" PRIMARY KEY ("ID_JOGADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."JOGADOR" MODIFY ("ID_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."JOGADOR" MODIFY ("DT_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."JOGADOR" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."JOGADOR" MODIFY ("ID_JOGADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TECNICO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TECNICO" ADD CONSTRAINT "FK_TIME_TECNICO" FOREIGN KEY ("ID_TIME")
	  REFERENCES "SYSTEM"."TIME" ("ID_TIME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JOGADOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."JOGADOR" ADD CONSTRAINT "FK_TIME_JOGADOR" FOREIGN KEY ("ID_TIME")
	  REFERENCES "SYSTEM"."TIME" ("ID_TIME") ENABLE;
	  
--------------------------------------------------------
-- Comentários
--------------------------------------------------------

comment on table time is '[Cadastro] Tabela para armazenamento de times.';
comment on column time.id_time is 'Codigo identificador do time.';
comment on column time.nome is 'Nome do time.';
